local languageConfig_ch =
    {
        language_0_0 = "网络连接失败，请重试",
        language_0_1 = "注册成功",
        language_0_2 = "邮箱格式错误",
        language_0_3 = "密码格式错误",
        language_0_4 = "该邮箱已注册",
        language_0_5 = "获取设备码错误",
        language_0_6 = "未知错误，不能注册",
        language_0_7 = "请输入账号",
        language_0_8 = "请输入密码",
        language_0_9 = "请再次输入确认密码",
        language_0_10 = "两次输入密码不同",
        language_0_11 = "账号或密码格式错误",
        language_0_12 = "账号不存在",
        language_0_13 = "登陆超时",
        language_0_14 = "登陆验证码错误",
        language_0_15 = "不能重复进行角色登陆",
        language_0_16 = "角色名重复",
        language_0_17 = "非法字符",
        language_0_18 = "请输入昵称",
        language_0_19 = "创建角色失败",
        language_0_20 = "[世界公告]",
        language_0_21 = "诸葛亮",
        language_0_22 = "吕布",
        language_0_23 = "挑战",
        language_0_24 = "查看",
        language_0_25 = "或取数据失败! 请重新获取。",
        language_0_26 = "详细",
        language_0_27 = "已有%d人申请 剩余%d件",
        language_0_28 = "你目前在%s的申请队列!排名第%d",
        language_0_29 = "是否放弃%s的申请?",
        language_0_30 = "加入%s的申请队列? ( 此操作不可以撤销 )",
        language_0_31 = "主公你的阵型尚未保存!是否退出？",
        language_0_32 = "放弃",
        language_0_33 = "保存",
        language_0_34 = "当前活跃度:%d点",
        language_0_35 = "%d点",
        language_0_36 = "提交成功",
        language_0_37 = "请输入你要提交的问题或内容",
        language_0_38 = "请输入QQ",
        language_0_39 = "登陆失败，请重试！",
        language_0_40 = "检测到当前NaverAppStore账号不能在该游戏中使用，请在NaverAppStore切换正确的账户，再重新登陆游戏！",
        language_0_41 = "支付失败!请检查当前NaverAppStore账号是否与Android设备关联成功，或重新登陆NaverAppStore账号!",
        language_0_42 = "检测到当前NaverAppStore账号与Android设备关联失败，或重新登陆NaverAppStore账号!",
        language_0_43 = "您已经购买了该产品，请重新登陆游戏使其应用于游戏当中！",
        language_0_45 = "确定要退出游戏吗？",
        language_0_46 = "检测到你未登陆NaverAppStore，请重新登陆NaverAppStore，再次尝试！",
        language_0_47 = "检测到你未安装NaverAppStore，请安装NaverAppStore，再次尝试！",
        language_0_48 = "恭喜你支付成功！",
        language_0_49 = "当前游戏登陆的Naver账号与设备关联的账号已更改，请重新登陆，再次尝试！",
        language_0_50 = "检测到当前NaverAppStore账号不能在该游戏中使用，请在NaverAppStore切换正确的账户，再重新登陆游戏！",
        language_0_51 = "支付失败。",
        language_0_52 = "检测到当前设备无google play service或版本过旧，请下载安装最新的版本后再次尝试。",


        language_Teach1 = "一品",
        language_Teach2 = "二品",
        language_Teach3 = "三品",
        language_Teach4 = "四品",
        language_Teach5 = "点击兵营",
        language_Teach6 = "选择招募",
        language_Teach7 = "长按招募10个短刀兵",
        language_Teach8 = "立刻完成招募",
        language_Teach9 = "关闭兵营",
        language_Teach10 = "打开武将传记",
        language_Teach11 = "选择董卓传",
        language_Teach12 = "点选岷县",
        language_Teach13 = "开始征战",
        language_Teach14 = "打开武将列表选主将",
        language_Teach15 = "选择主将",
        language_Teach16 = "阵型保存成功!",
        language_Teach17 = "阵型保存失败!",
        language_Teach18 = "部署士兵",
        language_Teach19 = "选择短刀兵",
        language_Teach20 = "主公请休息下！等级不够!%d级以后开启",
        language_Teach21 = "开",
        language_Teach22 = "关",
        language_Teach23 = "放置短刀兵到阵型位",
        language_Teach24 = "加载游戏资源!",
        language_Teach25 = "更新游戏资源!",
        language_Teach26 = "开始战斗",
        language_Teach27 = "%d级",
        language_Teach28 = "第%d关",
        language_Teach29 = "勇士试炼",
        language_Teach30 = "军师试炼",
        language_Teach31 = "统领试炼",
        language_Teach32 = "恭喜你!已经获得该卡片!赶快去邮箱领取吧。",
        language_Teach33 = "欢迎你下次在来哦。",
        language_Teach34 = "血战 第%d关",
        language_Teach35 = "恭喜！你已全部通关！",
        language_Teach36 = "可回收",
        language_Teach38 = "批量出售",
        language_Teach39 = "一键选择",
        language_Teach40 = "一键取消",
        language_Teach41 = "可回收金币:",
        language_Teach42 = "添加经验成功！",

        language_1_1 = "（",
        language_1_2 = "）",
        language_1_3 = "等级",
        language_1_4 = "生产速度：每小时",
        language_1_5 = "容量：",
        language_1_6 = "确定升至",
        language_1_7 = "级吗？",
        language_1_8 = "升级时间：",
        language_1_9 = "尚未获得!",
        language_1_10 = "正在升级中！",
        language_1_11 = "确定",
        language_1_12 = "玩家等级不够！",
        language_1_13 = "主城等级不够！",
        language_1_14 = "升级所需资源不够！",
        language_1_15 = "收货失败",
        language_1_16 = "未达到升级条件，不能升级",
        language_1_17 = "已达到最高等级，不能升级",
        language_1_18 = "该功能暂未开放，敬请期待",
        language_1_19 = "当前战功  %d%%",
        language_1_20 = "普通",
        language_1_21 = "困难",
        language_1_22 = "地狱",
        language_1_23 = "固定奖励",
        language_1_24 = "额外奖励",
        language_1_25 = "天梯系统繁忙，请稍后再试！",

        language_2_1 = "训练",
        language_2_2 = "升级",
        language_2_3 = "提速",
        language_2_4 = "总时间：",
        language_2_5 = "秒",
        language_2_6 = "分钟",
        language_2_7 = "小时",
        language_2_8 = "天",
        language_2_9 = "训练后总兵力：",
        language_2_10 = "立刻完成训练：",
        language_2_11 = "已领取",
        language_2_12 = "级",
        language_2_13 = "(已获得%d个)",
        language_2_14 = "提速还剩下：",
        language_2_15 = "队列",
        language_2_16 = "招募",
        language_2_17 = "暂停",
        language_2_18 = "兵营容量：",
        language_2_19 = "活动尚未开始",
        language_2_20 = "技能释放无合适对象",
        language_2_21 = "解锁兵种",
        language_2_22 = "总兵力",
        language_2_23 = "挑战次数已用完!明日再来",

        language_3_1 = "已达到最大等级",
        language_3_2 = "要求太学院达到",
        language_3_3 = "选择升级兵种",
        language_3_4 = "滑动屏幕以查看完整列表",
        language_3_5 = "星",
        language_3_6 = "攻击力:",
        language_3_7 = "生命值:",
        language_3_8 = "训练费用:",
        language_3_9 = "升星时间:",
        language_3_10 = "有兵种正在升级",
        language_3_11 = "资源不足",
        language_3_12 = "升星:",
        language_3_13 = "%d 元宝",
        language_3_14 = "获得奖励",
        language_3_15 = "%d关",
        language_3_16 = "战绩",

        language_4_1 = "主将",
        language_4_2 = "副将",
        language_4_3 = "军师",
        language_4_4 = "请先选择主将",
        language_4_5 = "：",
        language_4_6 = "总兵力",
        language_4_7 = "战力",
        language_4_8 = "%d/%d",
        language_4_9 = "详情",
        language_4_10 = "合计",
        language_4_11 = "第%d战",
        language_4_12 = "选择主将",
        language_4_13 = "选择副将",
        language_4_14 = "排名",
        language_4_15 = "获胜奖励积分",
        language_4_16 = "挑战",
        language_4_17 = "此次扫荡未获得任何物品!",
        language_4_18 = "获得奖励：5点活跃度!",

        language_5_1 = "称号",
        language_5_2 = "大将军",
        language_5_3 = "骠骑将军",
        language_5_4 = "车骑将军",
        language_5_5 = "查看英雄",
        language_5_6 = "战况",
        language_5_7 = "你挑战次数已用完!可以点击+按钮购买",
        language_5_8 = "获得经验：每小时",
        language_5_9 = "训练位：",
        language_5_10 = "总兵力：",
        language_5_11 = "所有军队：",
        language_5_12 = "解锁兵种",
        language_5_13 = "（",
        language_5_14 = "）",

        language_6_1 = "你挑战次数已满!无需购买",
        language_6_2 = "兑换成功!奖励已发邮件",
        language_6_3 = "是否花费%d元宝购买10点挑战次数",
        language_6_4 = "攻击值：",
        language_6_5 = "生命值：",
        language_6_6 = "训练费用：",
        language_6_7 = "攻速：",
        language_6_8 = "移速：",
        language_6_9 = "攻距：",
        language_6_10 = "人口值：",
        language_6_11 = "训练时间：",
        language_6_12 = "尚未获得30星，不能领取奖励!",
        language_6_13 = "尚未获得60星，不能领取奖励!",
        language_6_14 = "已达最大等级",
        language_6_15 = "元宝不足是否购买元宝?",
        language_6_16 = "升星时间：",
        language_6_17 = "升星：",
        language_6_18 = "星",
        language_6_19 = "剩余时间：",
        language_6_20 = "立即完成：",
        language_6_21 = "尚未开放，敬请期待！",
        language_6_22 = "体力不足！",
        language_6_23 = "挑战次数已用完！",
        language_6_24 = "平儿",
        language_6_25 = "挑战时间未到!",
        language_6_26 = "暂无被动",
        language_6_27 = "升阶之后将获得被动技能!",
        language_6_28 = "(主)",
        --language_6_29 = "(被)",
        language_6_30 = "当天只能购买10次挑战次数!明天再来吧。",

        language_7_1 = "是否花费%d元宝，购买%d体力？",
        language_7_2 = "生产：",
        language_8_1 = "武将",
        language_8_2 = "军师",
        language_8_3 = "统领",
        language_8_4 = "",
        language_8_5 = "帐号登录",
        language_8_6 = "数字和字母组成(不超过15个字符)",
        language_8_7 = "数字和字母组成(不超过15个字符)",
        language_8_8 = "注册",
        language_8_9 = "数字和字母组成(不超过15个字符)",
        language_8_10 = "注册",
        language_8_11 = "帐号中心",
        language_8_12 = "登录",
        language_8_13 = "注册新帐号",
        language_8_14 = "忘记帐号/密码？",
        language_8_15 = "消耗",
        language_8_16 = "生命 +%d%%",
        language_8_17 = "返还",
        language_8_18 = "遣散",
        language_8_19 = "已做为主将上阵!",
        language_8_20 = "已做为副将1上阵!",
        language_8_21 = "已做为副将2上阵!",
        language_8_22 = "已做为偏将%d上阵!",
        language_8_23 = "+%d积分",
        language_8_24 = "当前玩家正在被挑战!请等待或挑战其他玩家",
        language_8_25 = "攻击+%d%%，筹谋+%d%%",
        language_8_26 = "攻击 +%d%%",
        language_8_27 = "筹谋 +%d%%",
        language_8_28 = "+%d(印)",
        language_8_29 = "+%d(缘)",
        language_8_30 = "+%d(偏)",
        language_8_31 = "关卡尚未开启!敬请期待",
        language_8_32 = "筹谋值 %d/%d",
        language_8_33 = "筹谋值不足!",
        language_8_34 = "击杀",
        language_8_35 = "步",
        language_8_36 = "弓",
        language_8_37 = "骑",
        language_8_38 = "第一章",
        language_8_39 = "第二章",
        language_8_40 = "第三章",
        language_8_41 = "第四章",
        language_8_42 = "第五章",
        language_8_43 = "第六章",
        language_8_44 = "第七章",
        language_8_45 = "第八章",
        language_8_46 = "第九章",
        language_8_47 = "第十章",
        language_8_48 = "第十一章",
        language_8_49 = "第十二章",
        language_8_50 = "第十三章",
        language_8_51 = "第十四章",
        language_8_52 = "第十五章",
        language_8_53 = "第十六章",
        language_8_54 = "攻击 + %d",
        language_8_55 = "生命 + %d",
        language_8_56 = "筹谋 + %d",
        language_8_57 = "领兵 + %d",
        language_8_58 = "生命 + %d%%",
        language_8_59 = "体力已全部恢复",
        language_8_60 = "碎片",

        language_9_1 = "欢迎来到 三国必杀技",
        language_9_2 = "已获得税收",
        language_9_3 = "已获得卡牌，快去强化、进阶它吧！",
        language_9_4 = "恭喜主公！",
        language_9_5 = "失去连接!",
        language_9_6 = "金币箱",
        language_9_7 = "购买成功",
        language_9_8 = "今日还可购买：",
        language_9_9 = "购买",
        language_9_10 = "未知错误",
        language_9_11 = "1至3星卡才能自动添加",
        language_9_12 = "出售成功",
        language_9_13 = "生命+%d攻击+%d",
        language_9_14 = "后恢复一次。",
        language_9_15 = "角色卡已上阵",
        language_9_16 = "您选择了较强的武将",
        language_9_17 = "操作失败！",
        language_9_18 = "请选择主卡！",
        language_9_19 = "抽卡次数不够！",
        language_9_20 = "生命+%d%s攻击+%d%s领兵+%d%s筹谋+%d",
        language_9_21 = "(背包有      个)",
        language_9_22 = "购买次数已用完。",
        language_9_23 = "强化成功！",
        language_9_24 = "强化成功，提升%d级！",
        language_9_25 = "武魂不足，无法完成强化。",
        language_9_26 = "君主等级不够，武将等级不能超过君主等级！",
        language_9_27 = "所需资源不够！",
        language_9_28 = "强化等级已满，请进阶！",
        language_9_29 = "铜钱不足，是否前往征税？",
        language_9_30 = "元宝不足，是否前往充值？",
        language_9_31 = "请选择强化用的副卡！",
        language_9_32 = "请选择进阶用的祭品卡！",
        language_9_33 = "进阶所用祭品卡会消失，确定继续吗？",
        language_9_34 = "武魂不足，无法完成进阶。",
        language_9_35 = "已拥有",
        language_9_36 = "召唤成功，武将里可以查看它哦！",
        language_9_37 = "可召唤",
        language_9_38 = "碎片个数X",
        language_9_39 = "卡牌进阶过，是否出售？",
        language_9_40 = "刷新需要花费20元宝，是否继续？",
        language_9_41 = "第一章 第一关",
        language_9_42 = "第一章 第二关",
        language_9_43 = "第一章 第三关",
        language_9_44 = "关卡未通关！",
        language_9_45 = "寄件人：",
        language_9_46 = "生命：",
        language_9_47 = "攻击：",
        language_9_48 = "天赋：",
        language_9_49 = "克敌：",
        language_9_50 = "空",
        language_9_51 = "经验溢出，武将等级不能超过主公等级！主公是否要升级？",
        language_9_52 = "探马出现了意外，还请主公重新登录查看查看吧！",
        language_9_53 = "账号在其他地方登录，被迫下线",
        language_9_54 = "验证信息已过期，请重新登录服务器",
        language_9_55 = "进入游戏失败，请尝试重新登录服务器",
        language_9_56 = "网络较卡，请尝试再次登录服务器",
        language_9_57 = "账号或密码错误",
        language_9_58 = "请尝试重新登录服务器",
        language_9_59 = "(未开启)",
        language_9_60 = "扫荡功能将在12级以后开启!请主公继续努力!",
        language_9_61 = "刷新需要花费%d元宝，是否继续？",
        language_9_62 = "只有1星、2星卡可以一键选中",
        language_9_63 = "该武将已进阶至最高级！",
        language_9_64 = "君主等级要超过%d才能继续强化！",
        language_9_65 = "强化道具不足！",
        language_9_66 = "如果你没有符印，刷新需要20元宝，后面不再提示，是否确认？",
        language_9_67 = "刷新次数已用完！",
        language_9_77 = "是否花费%d元宝购买%d钱币？",
        language_9_78 = "您已都领取今天的在线奖励.",
        language_9_79 = "您已取消本次支付！",

        language_1000_15 = "等级达到最高",
        language_1000_16 = "缺少元宝",
        language_1000_17 = "缺少铜钱",
        language_1000_18 = "主城税收次数已用完",
        language_1000_500 = "招募士兵已满",
        language_1000_501 = "士兵等级已满不能升级",
        language_1000_502 = "士兵等级未满不能升阶",
        language_1000_503 = "没有士兵不能遣散士兵",
        language_1000_506 = "卡牌品质不合法",
        language_1000_507 = "每天免费招兵次数已满",
        language_1000_508 = "卡组已满，请清理",
        language_1000_509 = "卡组里没有合适的卡",
        language_1000_510 = "卡片mark报错",
        language_1000_511 = "最多选取6张卡片",
        language_1000_512 = "进阶材料不够，不能进阶",
        language_1000_513 = "服务器返回错误！",
        language_1000_514 = "邮件已领取！",
        language_1000_515 = "背包空间不足！",
        language_1000_516 = "武将包空间不足！",
        language_1000_517 = "超过物品叠加上限，领取失败！",

        language_555_1 = "步兵攻击一般，有着较高的生命力，可惜移动速度偏慢，适合作为肉盾。",
        language_555_2 = "骑兵有着极佳的移动速度和攻击力，擅长突击。适合作为输出兵种撕破对方防线。",
        language_555_3 = "弓兵具有较远的攻击距离，生命差。配合其他作战单位可以起到控制战局的效果。",

        language_message_1 = "1、测试服务器开启，当前为测试版本！",

        language_sevenstar_1 = "级开放",
        language_sevenstar_2 = "刷新成功！",
        language_sevenstar_3 = "刷新失败！",
        language_sevenstar_4 = "刷新一次需要消耗一个符印！如果存在隐藏属性，隐藏属性将会被重置！是否刷新？",
        language_sevenstar_5 = "请选择魂印！",
        language_sevenstar_6 = "这个武将没有进阶到真卡，请重新选择武将！",
        language_sevenstar_518 = "刷新达到最大次数！",

        language_task_1 = "领取成功！",
        language_task_2 = "领取失败！",
        language_task_3 = "活力值不足，不能领取这个奖励！",
        language_task_4 = "任务领奖已经领取！",
        language_task_11 = "领   取",
        language_task_12 = "前往",
        language_task_13 = "你没有加入公会，无法前往团队副本！",
        language_task_14 = "[任务报告]",
        language_task_15 = "[个人通知]",
        language_task_speaker_1 = "恭喜你！完成[出征任务]任务！",
        language_task_speaker_2 = "恭喜你！完成[招募神将]任务！",
        language_task_speaker_3 = "恭喜你！完成[武将升级]任务！",
        language_task_speaker_4 = "恭喜你！完成[士兵强化]任务！",
        language_task_speaker_5 = "恭喜你！完成[精英关卡]任务！",
        language_task_speaker_6 = "恭喜你！完成[天梯竞技场]任务！",
        language_task_speaker_7 =  "恭喜你！完成[主城任务]任务！",
        language_task_speaker_8 = "恭喜你！完成[七星坛]任务！",
        language_task_speaker_9 = "恭喜你！完成[团队副本]任务！",
        language_task_speaker_10 = "恭喜你！完成[英雄试练]任务！",
        language_task_speaker_11 = "恭喜你！完成[血战洛阳]任务！",
        language_task_speaker_12 = "恭喜你成功充值%d元宝！",

        language_backpack_1 = "使用成功！",
        language_backpack_2 = "使用成功！",
        language_backpack_3 = "不能使用！",

        language_logingif_1 = "你已经领取礼包！",

        language_novice_1000 = "是否跳过新手引导？",
        language_novice_100 = "主公，三国烽烟四起，请随我攻城掠地!",
        language_novice_101 = "战斗即将开始。开始战斗!",
        language_novice_102 = "战前准备，可以查看敌方阵型和武将，知己知彼百战不殆!",
        language_novice_103 = "点击继续",
        language_novice_104 = "重整阵容",
        language_novice_105 = "主公，大敌当前，让我们点击返回继续战斗！",
        language_novice_110 = "我们继续讲解武将卡进阶！",


        language_novice_0 = "空语句",
        language_novice_1 = "左上角是你的头像和武将的总血量，当总血量归零，就算战斗失败哦。",
        language_novice_2 = "点击武将头像就可以释放技能，释放技能后，不同的技能有不同的冷却CD时间。",
        language_novice_3 = "主公，酒馆聚集很多英雄豪杰。我们这就去招募一个武将吧。",
        language_novice_4 = "好不容易招到的武将，不派上阵就没有意义。我们快去布阵界面让武将上场。",
        language_novice_5 = "第一个将位是主将位，它将决定阵型，你的英雄已经迫不及待担当主将重任。主公，快速速派他上阵！",
        language_novice_6 = "选中武将头像，右边会显示他的属性。根据需求合理安排自己的阵容。",
        language_novice_7 = "点击上阵，该武将就会自动布进阵图，不过只有主将才能决定阵图的阵型。",
        language_novice_8 = "士兵虽然没有武将重要，但善于运用却能改变战局。点击阵图中间菱形框，士兵便会上阵。",
        language_novice_9 = "主公也可以通过手指滑动来布兵。",
        language_novice_10 = "主公，通过快捷操作（一键布阵），可以迅速把士兵布上阵。让我们快来试试。",
        language_novice_11 = "主公，我已经迫不及待和你一起去战斗。让我们带领部队去横扫敌军。",
        language_novice_12 = "主公，时机到了。武将之间有着相互克制。香香的技能能让那参谋的技能变成挠痒痒。",
        language_novice_13 = "连续签到已经开启，记得要去签到哦，大奖等着你！",
        language_novice_14 = "主公，你好神勇。让我们继续战斗吧。",
        language_novice_15 = "主公，据小道消息。这里可以领一个精壮勇士，让我们去领一个先。",
        language_novice_16 = "看来我们晚来一步啊。主公点击这个精瘦男子，带去凑个数量吧。",
        language_novice_17 = "有总比没有好。主公派那精瘦男子上阵吧。",
        language_novice_18 = "刚才那场战斗，主公表现的英明神武，已经有仰慕者给你来邮件了。我们去领取奖品吧！",
        language_novice_19 = "武将通过合并其他武将，来提升武将等级。让我们来试试。",
        language_novice_20 = "同星祭品卡能提升武将品质，从此我们的武将不再软弱啦！",
        language_novice_21 = "主公，其实技能是可以相互克制的！任他的火再强也抵不过我们的技能削弱！",
        language_novice_22 = "主公，我要走了。你要记得每天打副本，升级武将和士兵，参加天梯和血战等活动哦！温馨提示七星坛可以刷属性，大大提高武将战力。",
        language_novice_23 = "主公，点击头像可以设置开关音效，查看自己得信息而且输入兑换码还可以领奖哦！",
        language_novice_24 = "主公，这里可以用元宝招募你喜欢的武将哦，十连招募必定得到五星武将哦！",
        language_novice_1101 = "小伙伴们都迫不及待的等着你来挑战了。",
        language_novice_1102 = "天梯根据排名会发积分。积分能在积分商店兑换商品。天梯里可以布置防御阵型，我们来试试吧！",
        language_novice_1201 = "每天参加血战，可以获得元宝哦。请一定要记得参加。",
        language_novice_1202 = "亲，选择不同的挑战难度，得到星数不同。星作为每过五关BUFF购买的货币。选择一个挑战难度吧。",
        language_novice_1301 = "七星坛可以增长武将的属性。主公千万不要放过。",
        language_novice_1302 = "选一张真阶及其以上的武将，点击刷新就可以刷新武将属性。一次只要20元宝哦！",
        language_novice_1401 = "前方关卡敌军凶猛。主公可在此强化武将，以保万一。！",
        language_novice_1402 = "战事日趋白热化，主公可试试进阶武将，以得虎狼之师。！",
        language_novice_1403 = "我们可以一键选择素材卡，选好后确定就能提升武将的等级和实力了！",
        language_novice_1404 = "我们选择了主卡，只要选择同星级的副卡就可以进化武将了，进化后的武将实力会大大提升！",
        language_novice_1405 = "敌人越来越强大了，我们在去酒馆招募一名武将吧！",
        language_novice_1406 = "刚获得了一个三星武将，快让他上阵吧（他可是有群体伤害技能哦）！",
        language_novice_1407 = "让我们来提升士兵攻击、防御、血量！",
        language_novice_1408 = "我们先来强化骑兵吧，强化需要消耗武魂！",
        language_novice_1510 = "所谓乱世出英雄，主公可趁此风云之际招兵买马，训练自己的虎狼之师了。",
        language_novice_1511 = "恭喜主公再添一员大将。所谓养兵千日用兵一时，主公别光顾着打打杀杀记得每天来这里领取粮饷哦。",
        language_novice_1512 = "主公这里有方便之门可以直达战场！",
        language_novice_1610 = "五雷大法好，一技秒全家！",
        language_novice_1611 = "不行，我也得来个大招！",
        language_novice_1612 = "想活命的都让开，我要发飙了！",


        language_cjrenwu_0 = "任意武将升级到%d级",
        language_cjrenwu_1 = "任意武将卡进阶到%s",
        language_cjrenwu_2 = "任意兵种强化到%d阶%d级",
        language_cjrenwu_3 = "普通%d章%d小关通关",
        language_cjrenwu_4 = "主公等级提升到%d级",
        language_cjrenwu_5 = "获得%d张五星武将",
        language_cjrenwu_6 = "精英%d章%d小关通关",
        language_cjrenwu_10 = "获得奖励:",
        language_cjrenwu_20 = "等级:%d/%d级",
        language_cjrenwu_30 = "普",
        language_cjrenwu_31 = "真",
        language_cjrenwu_32 = "鬼",
        language_cjrenwu_33 = "神",
        language_cjrenwu_34 = "圣",
        language_cjrenwu_35 = "王",
        language_cjrenwu_36 = "皇",
        language_cjrenwu_40 = "%d阶%d级",
        language_cjrenwu_51 = "获得奖励: %d铜钱",
        language_cjrenwu_52 = "获得奖励: %d元宝",
        language_cjrenwu_53 = "获得奖励: %d武魂",

        language_pay_1 = "元",
        language_pay_2 = "元宝",
        language_pay_3 = "首充任意金额3倍赠送",
        language_pay_4 = "每日送%d元宝",
        language_pay_5 = "每日送120点体力",    

        language_ExpTransfer_1 = "该次转移能获得主卡%d％经验（放入经验转换丹能提升转换率）",
        --language_ExpTransfer_2 = "转移会获得相应补偿，快去邮件查收吧！",  
        language_ExpTransfer_3 = "转移成功！", 
        language_ExpTransfer_4 = "转移成功后，被转移武将会变为初使状态，是否继续？", 
        language_ExpTransfer_5 = "武将等级超过主公等级，经验已经溢出，是否继续？", 


        language_text_1 = "最大",
        language_text_2 = "购买",
        language_text_3 = "再招一次",
        language_text_4 = "返回",
        language_text_5 = "查看",
        language_text_6 = "跳过",
        
        --cs-----start
        tili_minute     = "%d分钟",
        login_User_already = "账户已存在",
        login_User_Success = "登陆成功",
        Register_User_Success = "注册成功",
        User_Not_Found = "账户不存在",
        User_Password_Error = "账户密码输入错误",
        None_Error = "未知错误",

        Server_State_1 = "正常",
        Server_State_2 = "关闭",
        Server_State_3 = "爆满",
        Server_State_4 = "维护",
        Server_State_5 = "即将开放",

        Server_State_Tip_2 = "服务器关闭中，无法登陆",
        Server_State_Tip_3 = "服务器忙碌，请少侠稍作休息",
        Server_State_Tip_4 = "服务器维护中，请见谅",
        Server_State_Tip_5 = "服务器暂未开放，敬请期待",
        Server_Not_Fount_Tip = "没有可以使用的服务器",

    
        Game_Logout_Error_0 = "探马出现了意外，还请主公重新登录查看查看吧！",
        Game_Logout_Error_1 = "账号在其他地方登录，被迫下线",
        Game_Logout_Error_2 = "验证信息已过期，请重新登录服务器",
        Game_Logout_Error_3 = "进入游戏失败，请尝试重新登录服务器",
        Game_Logout_Error_4 = "账号已更改",
        Game_Logout_Error_5 = "玩家已失效",
        Game_Logout_Error_6 = "玩家数量已满",
        Game_Logout_Error_7 = "不在服务器中",
        Game_Logout_Error_8 = "系统其他错误",
        Game_Logout_Error_9 = "玩家被封禁",


        ui_LoadingView_1 = "抱歉，资源解压出错，请重启客户端",
        ui_LoadingView_2 = "抱歉，获取资源列表出错，请检查网络是否连接",
        ui_LoadingView_3 = "抱歉，检查游戏版本出错，请检查网络是否连接，重启客户端",
        ui_LoadingView_4 = "抱歉，下载文件出错，请检查网络是否连接",
        ui_LoadingView_5 = "游戏大版本更新，请到官网下载最新版本",
        ui_LoadingView_6 = "该次游戏更新需要重启客户端",
        ui_LoadingView_7 = "(已下载 %0.2fM/共 %0.2fM)",
        -- ui_LoadingView_8 = "获取网络数据",
        ui_LoadingView_9 = "更新通知",
        ui_LoadingView_10 = "主公，版本已经更新，是否要下载？",
        ui_LoadingView_11 = "点击下载",

        ui_LoginView_2 = "最近登录",
        ui_LoginView_3 = "更多服务器列表",
        ui_LoginView_4 = "数字和字母组成(不超过15个字符)",

        ui_MainView_1 = "下次体力恢复:",
        ui_MainView_2 = "恢复全部体力:",
        ui_MainView_3 = "恢复时间间隔:",
        ui_MainView_4 = "已买体力次数:",

        ui_LevelUpView_1 = "升级已恢复所有体力",

        Guide_OpenTip_sd = "通关副本并且获得3星评价后，就可以使用扫荡功能啦，这么酸爽的功能快一起去体验下吧！",
        Guide_OpenTip_shop = "已达到8级，能利用商店菜单。",
        Guide_OpenTip_sbsj = "士兵升级功能开启",
        Guide_OpenTip_pj = "偏将功能开启",
        Guide_OpenTip_tiant = "天梯功能开启",
        Guide_OpenTip_maincity = "主城系统开启",
        Guide_OpenTip_qxt = "七星坛系统开启",
        Guide_OpenTip_gh = "工会系统开启",
        Guide_OpenTip_wjsl = "武将试炼系统开启",
        Guide_OpenTip_xuez = "血战系统开启",

        --战斗系统
        resetJYgk_1 = "挑战次数已经用完，是否花费%d元宝购买重置挑战？",
        resetJYgk_2 = "今日已重置%d次，重置精英关卡次数不足，提升VIP等级可获更多次数。",
        resetJYgk_3 = "重置成功！",

        ui_CombatView_shu = "蜀国大军1",
        ui_CombatView_wu = "吴国大军1",
        ui_CombatView_1 = "右下角头像闪光表示武将可以使用大招，点击头像释放大招",
        ui_CombatView_2 = "战场中许多敌人太过弱小，这时候就能使用自动战斗了!",
        ui_CombatView_tip_3 = "等级10级可以使用",
        ui_CombatView_invalid = "战斗无效，本次战斗超时",

        --关卡
        ui_CombatView_Fb_1 = "第一章",
        ui_CombatView_Fb_2 = "第二章",
        ui_CombatView_Fb_3 = "第三章",
        ui_CombatView_Fb_4 = "第四章",
        ui_CombatView_Fb_5 = "第五章",
        ui_CombatView_Fb_6 = "第六章",
        ui_CombatView_Fb_7 = "第七章",
        ui_CombatView_Fb_8 = "第八章",
        ui_CombatView_Fb_9 = "第九章",
        ui_CombatView_Fb_10 = "第十章",
        ui_CombatView_Fb_11 = "第十一章",
        ui_CombatView_Fb_12 = "第十二章",
        ui_CombatView_Fb_13 = "第十三章",
        ui_CombatView_Fb_14 = "第十四章",
        ui_CombatView_Fb_15 = "第十五章",
        ui_CombatView_Fb_16 = "第十六章",
        ui_CombatView_Fb_17 = "第十七章",
        ui_CombatView_Fb_18 = "第十八章",
        ui_CombatView_Fb_19 = "第十九章",
        ui_CombatView_GkIndex = "第%d章",

        ui_NewPlayerView_1 = "请输入你的大名2",

        ui_MinFbSelectView_1 = "等级限制，君主%d级开启",
        ui_MinFbSelectView_2 = "下一个地方的精英副本已经开放.",

        ui_FbSelectView_1 = "无主将，不出征，请前往布阵！",

        --cs-----end
        --tyj----start
        --vip相关
        language_vipDescribe = {  
            --    "[fontColor=f75d85]hello world[/fontColor][fontColor=ffffff]你好[/fontColor]" 
            -- "无任何特权",
            --       "每日可领取<金币>[%d]",
            --       "每日可领取<刷新令>[%d]个",
            -- "每日可购买<体力>[%d]次",
            --       "每日可购买<金币>[%d]次",
            --       "可以开启<加速>功能（ps:暂未完成）",
            --       "每日可以<重置精英关卡>[%d]次",
            -- "可以开启<10连扫荡>",
            -- "可以购买<天梯重置>[%d]次",
            -- "<主城任务>次数+[%d]",
            -- "<血战>挑战次数+[%d]",
            "[fontColor=ffffff]无任何特权[/fontColor]",
            "[fontColor=ffffff]每日可领取[/fontColor][fontColor=f75d85]金币[/fontColor][fontColor=FFA500]%d[/fontColor]",
            "[fontColor=ffffff]每日可领取[/fontColor][fontColor=f75d85]体力丹[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]个[/fontColor]",
            "[fontColor=ffffff]每日可领取[/fontColor][fontColor=f75d85]扫荡令[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]个[/fontColor]",
            "[fontColor=ffffff]每日可购买[/fontColor][fontColor=f75d85]体力[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=ffffff]每日可购买[/fontColor][fontColor=f75d85]金币[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=ffffff]可以开启[/fontColor][fontColor=f75d85]加速[/fontColor][fontColor=ffffff]功能[/fontColor]",
            "[fontColor=ffffff]每日可以[/fontColor][fontColor=f75d85]重置精英关卡[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=ffffff]可以开启[/fontColor][fontColor=f75d85]10连扫荡[/fontColor]",
            "[fontColor=ffffff]可以购买[/fontColor][fontColor=f75d85]天梯重置[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=f75d85]主城任务[/fontColor][fontColor=ffffff]次数加[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=f75d85]血战[/fontColor][fontColor=ffffff]挑战次数加[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            "[fontColor=f75d85]商店刷新[/fontColor][fontColor=ffffff]次数加[/fontColor][fontColor=FFA500]%d[/fontColor][fontColor=ffffff]次[/fontColor]",
            
        },
        --活动相关
        language_activityHero=
        {
            tips = "六星神将",
            rankDescribe = { "排名[1]可获得<张辽(幻)>、<曹操>、<司马昭>",
                "排名[2]到[3]可获得<张辽(幻)>、<曹操>",
                "排名[4]到[20]可获得<张辽(幻)>",
                "排名[21]到[50]可获得<曹操>",
            --"排名[1]可获得<曹操>、<关羽>",
            },
        },
        language_attrConfig = {{"<",">",cc.c3b(255,0,0)}, --为字符添加颜色属性
            {"[","]",cc.c3b(255,165,0)},
        },

        --布阵系统
        language_embattle_1 = "阵型信息有改动，是否保存？",
        language_embattle_2 = "没有主将上阵，无法完成一键布阵！",
        language_embattle_3 = "请先选择一位武将吧！",
        language_heyizhen     = "鹤翼阵",
        language_zhuixingzhen = "锥形阵",
        language_gouxingzhen  = "钩形阵",
        language_changshezhen = "长蛇阵",
        language_yuanxingzhen = "圆形阵",
        language_yanxingzhen  = "雁形阵",
        --选将系统
        language_selectHero_1 = "该英雄已作为%s上阵，请重新选将！",
        language_selectHero_2 = "主将",
        language_selectHero_3 = "副将",
        language_selectHero_4 = "偏将",
        language_selectHero_5 = "没有符合条件的英雄！去招募招一个看看吧",
        language_selectHero_6 = "请选择一个武将",
        language_selectHero_7 = "该武将已作为%s上阵，是否继续？",
        language_selectHero_8 = "不能替换主将位置的武将！", 
        language_selectHero_9 = "已有该名字武将上阵！", 
        --天梯系统
        language_tianTi_1 = "挑战次数已满，不用再购买了",
        language_tianTi_2 = "恭喜你，购买挑战次数成功!",
        language_tianTi_3 = "购买次数已满!",
        language_tianTi_4 = "大将军",
        language_tianTi_5 = "骠骑将军",
        language_tianTi_6 = "车骑将军",
        language_tianTi_7 = "今日BUFF阵型：",
        --七星坛系统
        language_sevenStar_1 = "符文与元宝不足",
        language_sevenStar_2 = "请选择需要刷新的星印",
        language_sevenStar_3 = "满级相同属性可激活",
        language_sevenStar_4 = "法抗",
        language_sevenStar_5 = "攻击",
        language_sevenStar_6 = "生命",
        language_sevenStar_7 = "法术",
        --任务系统
        language_tyj_task_1 = "跳转类型",
        language_tyj_task_2 = "精英关卡未开启！",
        language_tyj_task_3 = "团队副本未开启！",
        language_tyj_task_4 = "任务描述",
        language_tyj_task_5 = "完成次数",
        language_tyj_task_6 = "点",
        language_tyj_task_7 = "文字",
        --英雄试炼系统
        language_heroShiLian_1 = "本次试炼已经完成！明天再来吧！",
        language_heroShiLian_2 = "恭喜你！已经成功获得神秘卡牌。赶快点击领取吧！",
        language_heroShiLian_3 = "恭喜你！已经成功获得来访神将。赶快点击领取吧！",
        language_heroShiLian_4 = "成功挑战恶梦难度100%获得来访神将！",
        language_heroShiLian_5 = "挑战的难度越高获得的战功越多！",
        --活动系统
        language_activity_1 = "领取奖励成功！",
        language_activity_2 = "天:时:分:秒",
        --vip系统
        language_vip_1 = "领取",
        language_vip_2 = "已领取",
        language_vip_3 = "领取VIP奖励成功",
        language_vip_4 = "礼包",
        language_vip_5 = "特权",
        language_vip_tip_1 = "VIP3 开启战斗加速功能",
        --扫荡系统
        language_sweep_1 = "第%d战",
        language_sweep_2 = "扫荡%d次",
        language_sweep_3 = "别点了，你当前的体力不足以这么多次扫荡！",
        language_sweep_4 = "别点了，没有足够的扫荡令！",
        --道具系统
        language_prop_1 = "该装备已被武将穿戴，不能出售！",
        language_prop_2 = "该装备品质较高，是否出售该装备？",
        language_prop_3 = "出售装备成功！",
        language_prop_4 = "改名成功！",
        language_prop_5 = "修改名字失败，名字不能为空！",
        language_prop_6 = "发送消息成功！",
        language_prop_7 = "发送消息失败，消息不能为空！",
        language_prop_8 = "使用体力丹成功！",
        language_prop_9 = "背包已满，添加道具失败",
        language_prop_10 = "该道具不存在！",
        language_prop_11 = "附加",
        language_prop_12 = "该装备无附加属性",
        language_prop_13 = "请选择道具",
        language_prop_14= "出售道具成功！",
        language_prop_15= "出售所有该道具可以回收金币：",
        --装备系统
        language_equip_1 = "该位置没有武将，是否上阵一个武将？",
        language_equip_2 = "当前选择装备已被其他武将穿戴，是否继续穿戴？",
        language_equip_3 = "该装备已不能被强化了！",
        language_equip_4 = "该装备已不能被合成了！",
        language_equip_5 = "很遗憾，本次强化失败，再试一次吧！",
        language_equip_6 = "很遗憾，本次洗练失败，再试一次吧！",
        language_equip_7 = "很遗憾，本次合成失败，再试一次吧！",

        --固定UI文字

        ui_activityHero_1 = "活动时间：",
        ui_activityHero_2 = "活动倒计时：",
        ui_activityHero_3 = "再次购买",
        ui_activityHero_4 = "次之后，获得",
        ui_activityHero_5 = "当前排名：",
        ui_activityHero_6 = "当前积分：",

        ui_equip_1 = "名称：",
        ui_equip_2 = "攻击：",
        ui_equip_3 = "出售价格:",
        ui_equip_4 = "出售",
        ui_equip_5 = "替换",
        ui_equip_6 = "装备",

        ui_selectHero_1 = "战力",
        ui_selectHero_2 = "攻击",
        ui_selectHero_3 = "生命",
        ui_selectHero_4 = "法术",
        ui_selectHero_5 = "法防",
        ui_selectHero_6 = "领兵",
        ui_selectHero_7 = "阵型",
        ui_selectHero_8 = "武力",
        ui_selectHero_9 = "智力",
        ui_selectHero_10 = "统御",
        ui_selectHero_11 = "暴击",

        ui_heroShiLian_1 = "当前战功",

        ui_prop_1 = "道",
        ui_prop_2 = "具",
        ui_prop_3 = "装",
        ui_prop_4 = "备",

        ui_sevenStar_1 = "请先选择真阶或真阶以上的卡片！",

        ui_signReward_1 = "你已连续登陆",
        ui_signReward_2 = "天",
        ui_signReward_3 = "温馨提示：连续登陆可领取豪华大奖！",

        ui_sweep_1 = "扫荡令:",
        ui_sweep_2 = "体力消耗:",

        ui_task_1 = "当前活跃度:",

        ui_tianTi_1 = "后恢复一次机会",
        ui_tianTi_2 = "剩余挑战次数",
        ui_tianTi_3 = "当前战力",
        ui_tianTi_4 = "当前排名",
        ui_tianTi_5 = "当前积分",

        ui_xueZhan_1 = "剩余",

        ui_payInf_1 = "首充任意金额3倍赠送",
        --tyj----end
        --lk--
        language_City_1 = "任务次数已用完",
        language_City_2 = "已有武将在执行任务",
        language_City_3 = "是否花费10元宝加速任务",
        language_City_4 = "元宝不足，是否购买元宝？",
        language_City_5 = "探索寻宝等级提升级到%d，宝物概率提升至%d.",
        language_City_7 = "维护冶安等级提升级到%d，元宝增加提升至%d.",
        language_City_9 = "整顿商业等级提升级到%d，金币增加提升至%d.",



        language_Compound_1 = "关卡ID",
        language_Compound_2 = "(未开启)",
        language_Compound_3 = "此关卡未通关",

        language_Enhance_1 = "君主等级不够",
        language_Enhance_2 = "请先添加需要升级的卡",
        language_Enhance_3 = "武将等级不能超过君主等级，不能升级!",
        language_Enhance_4 = "请添加副卡",
        --language_Enhance_5 = "武将等级不能超过君主等级，不能升级",
        language_Enhance_6 = "经验溢出，是否升级？",
        language_Enhance_7 = "生命",
        language_Enhance_8 = "攻击",
        --language_Enhance_9 = "领兵",
        --language_Enhance_10 = "筹谋",
        language_Enhance_11 = "请查看添加武将位置是否都有武将",
        language_Enhance_12 = "武将等级达到%d级可以进阶",
        language_Enhance_13 = "才可进阶",
        language_Enhance_14 = "武将已经进阶到最大阶",
        language_Enhance_15 = "没有合适的武将添加",
        language_Enhance_16 = "武将等级不能超过主公等级，会损失一些经验，继续吗？",

        language_Enlist_1 = "今日免费次数：",
        language_Enlist_2 = "你有免费抽武将的机会哦！",
        language_Enlist_3 = "免费",
        language_Enlist_4 = "时间后免费",
        language_Enlist_5 = "今日免费次数已用完",
        language_Enlist_6 = "今次必出5星武将",
        language_Enlist_7 = "再抽",
        language_Enlist_8 = "次出现5星武将",
        language_Enlist_9 = "武将已招满",
        language_Enlist_10 = "金币不足",
        language_Enlist_11 = "元宝不足",
        
        
        language_Discount_1 = "(最多领取%d/3次)",

        language_Hero_1 = "确认",
        language_Hero_2 = "你选择了强力武将！",
        language_Hero_3 = "最多可选择6张",
        language_Hero_4 = "没有可以进阶的武将",
        language_Hero_5 = "出售已进阶武将，获得%d返还武魂",

        language_CardIn_1 = "技能名字",
        language_CardIn_2 = "技能描述",
        language_CardIn_3 = "(被)",
        language_CardIn_4 = "暂无被动",
        language_CardIn_5 = "升到一定阶数后将获得被动技能",
        language_CardIn_6 = "还未获得该武将！",

        language_Shop_1 = "刷新次数不够，vip等级越高，刷新次数越多。",
        language_Shop_2 = "该商品已售馨",
        language_Shop_3 = "下次更新:",
        --language_Shop_3 = "购买成功",


        language_Chat_1 = "级",
        ui_language_Chat_2 = "点击输入",
        
        language_Rank_1 = "我的排名: %d",
        language_Rank_2 = "未获取玩家数据", 
        language_Rank_3 = "未获取公会数据", 
        language_Rank_4 = "未加入公会", 
        language_Rank_5 = "未上榜", 
        language_Rank_6 = "目前没有公会上榜", 
        language_Rank_7 = "目前没有玩家上榜",
        
        language_GuildBattle_1 = "未开放",
        language_GuildBattle_2 = "竟价成功",
        language_GuildBattle_3 = "第一名",
        language_GuildBattle_4 = "第二名",
        language_GuildBattle_5 = "第三名",
        language_GuildBattle_6 = "竟价%d公会资金",
        language_GuildBattle_7 = "公会占领",
        language_GuildBattle_8 = "您已第%d次购买复活，需要花费%d元宝",
        language_GuildBattle_9 = "占领收益：",

        language_HuoDong_1 = "%d天%02d时%02d分",
        language_HuoDong_2 = "活动已过期",
        language_HuoDong_3 = "活动倒计时：",
        language_HuoDong_4 = "月",
        language_HuoDong_5 = "日",
        language_HuoDong_6 = "级成长基金",
        language_HuoDong_7 = "达到%d级可领取%d元宝",
        language_HuoDong_8 = "级可领取",
        language_HuoDong_9 = "元宝",
        language_HuoDong_10 = "元",
        --language_HuoDong_11 = "领取成功",
        language_HuoDong_12 = "活动未开启",

        language_Soldiers_1 = "生命",
        language_Soldiers_2 = "攻击",
        language_Soldiers_3 = "法术",
        language_Soldiers_4 = "法防",
        language_Soldiers_5 = "克敌",

        language_Soldiers_6 = "此关卡未通关",
        language_Soldiers_7 = "君主等级达到",
        language_Soldiers_8 = "级才可进阶",
        language_Soldiers_9 = "步兵攻击一般，有着较高的生命力，可惜移动速度偏慢，适合作为肉盾。",
        language_Soldiers_10 = "骑兵有着极佳的移动速度和攻击力，擅长突击，适合作为输出兵种撕破对方防线。",
        language_Soldiers_11 = "弓兵有着较远的攻击距离，生命低，配合其他作战单位可以起到控制战局的效果。",
        language_Soldiers_12 = "士兵%d级才可进阶",

        language_Union_1 = "元宝不够",
        language_Union_2 = "公会名不能为空",
        language_Union_3 = "请输入公会id",
        language_Union_4 = "级",
        language_Union_5 = "长老",
        language_Union_6 = "会长",
        language_Union_7 = "成员",
        language_Union_8 = "撤消长老",
        language_Union_9 = "升为长老",
--        language_Union_10 = "第",
--        language_Union_11 = "章",
        language_Union_12 = "进度",
        language_Union_133 = "开启副本",
        language_Union_144 = "攻打副本",
        language_Union_15 = "最后上线时间",
        language_Union_16 = "七日活跃贡献",
        language_Union_17 = "副本挑战次数",
        language_Union_18 = "获得体力",
        language_Union_19 = "任何人不能加入",
        language_Union_20 = "需要申请加入",
        language_Union_21 = "所有人都可以加入",
        language_Union_22 = "开启副本",
        language_Union_23 = "攻打副本",
        language_Union_24 = "第%d章",
        language_Union_25 = "进度",
        language_Union_26 = "等级不足",

        language_Union_28 = "你确认退出公会吗？",
        language_Union_29 = "当前章节未通关！",
        language_Union_30 = "获得体力！",
        language_Union_31 = "公会名不能为空！",
        language_Union_32 = "公会名",
        language_Union_33 = "公会ID",
        language_Union_34 = "公会解散后不能恢复，确认解散公会吗？",
        language_Union_35 = "让出会长职位，才能退出公会！",
        language_Union_36 = "请输入公会名(不超过10个字符)",
        language_Union_37 = "%d铜钱=%d公会资金",
        language_Union_38 = "%d元宝=%d公会资金",
        language_Union_39 = "累计捐献：%d",
        language_Union_40 = "公会资金：%d",
        language_Union_41 = "公会战暂未开放，敬请期待!",
        language_Union_42 = "公会捐献暂未开启！",

        language_Union_43 = "在线",
        
        
        language_IntegralShop_1 = "达到购买上限",
        language_IntegralShop_2 = "达到购买下限",
            

        language_BigCard_1 = "进阶到更高阶可解锁！", 


        language_Functions_1 = "元宝不足，是否购买元宝？", 
        language_Functions_2 = "购买体力成功", 
        language_Functions_3 = "购买体力次数已满！", 
        language_Functions_4 = "购买金币次数已满！", 


        language_Login_1 = "网络连接错误", 
        
        language_MinFb_1 = "该章精英关卡尚未开通！",
        language_MinFb_2 = "该章团队关卡尚未开通！",
        language_MinFb_3 = "关卡未开放！",
        language_MinFb_4 = "关卡已通过！",
        language_MinFb_5 = "关卡未解锁！",
        language_MinFb_6 = "该章副本尚未开通！",

        language_Pokedex_1 = "收集进度：",
        language_Pokedex_2 = "暂未收集到该神秘武将，不能查看详细信息！",

        language_ChaDui_1 = "个",
        --language_ChaDui_2 = "分钟后",
        language_ChaDui_3 = "你已经是第一名了！",



        ui_CardIn_1 = "属性",
        --ui_CardIn_2 = "生命",
        ui_CardIn_3 = "武力",
        --ui_CardIn_4 = "攻击",
        ui_CardIn_5 = "智力",
        --ui_CardIn_6 = "法术",
        ui_CardIn_7 = "统御",
        --ui_CardIn_8 = "法防",
        ui_CardIn_9 = "阵型",
        ui_CardIn_10 = "技能",
        --ui_CardIn_11 = "技能名字",
        ui_CardIn_12 = "缘份",
        --ui_CardIn_13 = "缘份名",
        ui_CardIn_14 = "描述",

        ui_Chat_1 = "免费",

        ui_City_1 = "探索寻宝  LV",
        ui_City_2 = "宝物数量:",
        ui_City_3 = "升级所需经验:",
        ui_City_4 = "任务倒计时:",
        ui_City_5 = "开始执行任务",
        ui_City_6 = "今日剩余次数：",
        ui_City_7 = "维护冶安  LV",
        ui_City_8 = "元宝增加:",
        ui_City_9 = "整顿商业  LV",
        ui_City_10 = "金币增加:",


        --ui_Compound_1 = "人物名",
        ui_Compound_2 = "已拥有：",
        --ui_Compound_3 = "物品名",
        ui_Compound_4 = "你还没有获得任何碎片，天梯的积分商城可以购买碎片。",



        ui_Enhance_1 = "武将名",
        ui_Enhance_2 = "下一级升级经验",
        ui_Enhance_3 = "获得经验",
        ui_Enhance_4 = "消耗铜钱",
        ui_Enhance_5 = "1至3星武将才能自动添加",
        ui_Enhance_6 = "武将等级达到     级可以进阶",
        ui_Enhance_7 = "消耗武魂",
        ui_Enhance_8 = "您的武将已进阶到最大阶！",



        ui_HuoDong_1 = "活动介绍:",
        ui_HuoDong_2 = "活动时间:",

        ui_Mail_1 = "邮件标题",

        ui_Soldiers_1 = "已拥有",
        ui_Soldiers_2 = "克敌",
        ui_Soldiers_3 = "已进阶到最大阶数。",

        ui_Union_1 = "最后7日贡献活跃：",
        ui_Union_2 = "最后上线时间：",
        ui_Union_3 = "公会成员数量：",
        ui_Union_4 = "入会申请",
        ui_Union_5 = "团队副本",
        ui_Union_6 = "要求公会活跃度：",
        ui_Union_7 = "膜拜大神",
        ui_Union_8 = "只有膜拜君主等级比自己高的玩家，每次成功膜拜，都可以获得一定的体力值，被膜拜的玩家会获得金币奖励。",
        ui_Union_9 = "今日剩余膜拜次数：",
        ui_Union_10 = "你累计可以领取奖励：",
        ui_Union_11 = "公会日志",
        ui_Union_12 = "选择图标",
        ui_Union_13 = "发送至：",
        ui_Union_14 = "公会全员",
        ui_Union_15 = "成员管理",
        ui_Union_16 = "公会成员数量",
        ui_Union_17 = "选择膜拜方式",
        ui_Union_18 = "获得体力  30",
        ui_Union_19 = "获得体力  60",
        ui_Union_20 = "公会留言",
        ui_Union_21 = "公告修改",
        ui_Union_22 = "公会设置",
        ui_Union_23 = "公会图标：",
        ui_Union_24 = "公会类型：",
        ui_Union_25 = "入会最小等级：",
        ui_Union_26 = "公会ID:",
        ui_Union_27 = "成员:",
        ui_Union_28 = "公会宣言：",
        ui_Union_29 = "需要     级",
        ui_Union_30 = "公会名称：",
        ui_Union_31 = "创建花费：",
        ui_Union_32 = "发送成功：",
        ui_Union_33 = "输入邮件主题",
        ui_Union_34 = "输入邮件内容",
        ui_Union_35 = "输入公告",
        ui_Union_36 = "输入公会留言",

        lk_common_1 = "生命",
        lk_common_2 = "攻击",
        lk_common_3 = "法术",
        lk_common_4 = "法防",
        lk_common_5 = "已经拥有个数:",
        
        ui_combatBefore_1 = "总战力",

        --lk--

        cs_FbSelect_1 = "地图尚未开放，敬请期待!",

        --新手引导相关
        --cs--
        ------
        --lk--
        guide_1_1 = "点击签到吧，以后记得每天按时签到哦",
        guide_1_2 = "点击第一天签到",
        guide_1_3 = "东西到手点击关闭吧",

        guide_2_1 = "点击招募，这里可是聚集这三国的许多名将哦",
        guide_2_2 = "点击元宝抽奖，这里可以抽到3到6星的，人品爆发抽到6星也说不定哦",
        guide_2_3 = "嗯，结果马马虎虎下次再努力吧，点击返回",

        guide_3_1 = "点击金币抽奖，这里可是聚集这三国的许多名将哦",
        guide_3_2 = "好了，武将有了接下来就点击返回吧",

        guide_4_1 = "点击布阵，部队的阵形是根据主将来的哦",
        guide_4_2 = "点击添加武将卡，这次我就帮你选主将吧，下次请根据主公自己需要更换",
        guide_4_3 = "就选择他武将作为主将吧",
        guide_4_4 = "让他上阵做主将吧",
        guide_4_5 = "再选择一个副将吧",
        guide_4_6 = "就选择他作为副将吧",
        guide_4_7 = "让他上阵吧",
        guide_4_8 = "点击一键布阵，一键布置士兵，士兵是存在克制的，下次主公不妨手动布置",
        guide_4_9 = "点击保存，这样就算布阵完了",
        guide_4_10 = "点击返回，现在可以开始作战了",

        guide_5_1 = "点击出征，准备开战吧",
        guide_5_2 = "点击第一章节图标，先从最简单的来吧",
        guide_5_3 = "点击战斗，每场战斗是会扣除相应体力值的，以后还请主公合理选择",
        guide_5_4 = "点击开战，如果感觉有困难，主公可以重新设置阵形和兵种再开战",
        guide_5_5 = "战果马马虎虎点击确定吧，",
        guide_5_6 = "进阶下武将实力会更上一层楼，点击返回",
        guide_5_7 = "点击返回",

        guide_6_1 = "点击升级吧",
        guide_6_2 = "点击武将进阶让武将变得更强大吧",
        guide_6_3 = "点击此处添加武将卡",
        guide_6_4 = "这次就选他吧",
        guide_6_5 = "点击进阶，进阶会消耗一定的铜钱和武魂哦",
        guide_6_6 = "进阶完成点击关闭吧",
        guide_6_7 = "嗯，实力变强了点了，去战斗下看看，点击返回",
        --guide_6_8 = "点击返回按钮",

        guide_7_1 = "点击出征吧",
        guide_7_2 = "点击第一章节图标，这次我们打第二关",
        guide_7_3 = "点击战斗，让敌人见识下进阶后厉害",
        guide_7_4 = "别犹豫开战吧",
        guide_7_5 = "这次也很简单不用重新布阵确定吧",

        guide_8_1 = "轻轻松松胜利，主公我们再推一关",
        guide_8_2 = "主公在战斗开始前，我们还可以布阵，我们来试试吧",
        guide_8_3 = "主公，想要手动布置士兵就需要先第一步是将已经上阵士兵撤退下来，点击撤军按钮将上阵士兵撤退.",
        guide_8_4 = "完成撤军后，我们就可以通过点选士兵头像然后再点击放置位置完成布置士兵，现在我们先来布置一队骑兵",
        guide_8_5 = "布置完骑兵后我们可以考虑在骑兵后面布置一批用于输出的弓箭手，现在我们来布置弓箭士兵",
        guide_8_6 = "点击开战",
        guide_8_7 = "刚刚战斗积累了点经验卡，我们升级下武将吧，点击返回",
        guide_8_8 = "点击返回",

        guide_9_1 = "点击升级吧",
        guide_9_2 = "这次我们升级武将，点击武将升级",
        guide_9_3 = "点击此处添加武将卡",
        guide_9_4 = "这次我们就选他吧",
        guide_9_5 = "点击自动添加，系统会为主公自动筛选符合条件的卡来提供经验",
        guide_9_6 = "点击升级，升级会消耗一定的武将卡和铜钱",
        guide_9_7 = "升级完毕点击关闭吧",
        guide_9_8 = "武将实力上升了再配备点装备就完美了，点击返回",

        guide_10_1 = "点击背包吧",
        guide_10_2 = "看见这宝箱没？点击吧",
        guide_10_3 = "这是装备宝箱，打开吧",
        guide_10_4 = "哦，是武器啊，嗯直接提升攻击也不错",
        guide_10_5 = "嗯，马马虎虎的装备点击返回吧",

        guide_11_1 = "接下来就装备吧点击装备按钮",
        guide_11_2 = "去选择一件装备吧",
        guide_11_3 = "就选这件装备吧",
        guide_11_4 = "穿上它吧，这样对应阵形位置上的武将就拥有这件装备的提供的属性了",
        guide_11_5 = "完美提升实力去战斗下吧，点击返回",

        guide_12_1 = "点击出征吧",
        guide_12_2 = "点击第一章节图标，这次我们选第三关吧",
        guide_12_3 = "点击战斗，后面的操作就交给主公你了，那么以后有缘再见",

        guide_14_1  = "在成就菜单可以获取目前为止主公达成的成就的奖励。",
        guide_14_2  = "主公已达成6级，可领取首次成就奖励。",
        guide_14_3  = "根据成就可以拿到更多的元宝和银币，一定要努力达成所有成就哦！",

        guide_15_1  = "其次我们了解一下任务。请选择任务菜单。",
        guide_15_2  = "主公刚好获得了25分，能领取奖励哦。",
        
        guide_16_1  = "点击出征任务的移动按钮执行剩下的任务。",
        
        guide_100_1 = "在商店可购买武将，装备箱，符印等多样的道具。",
        guide_100_2 = "购买以下武将碎片吗？这次特别添加了免费的商品，请直接购买看看哦。",
        
        guide_101_1 = "获得的碎片会存放在合成里面，当数量足够时就能够将碎片合成武将了，接下来我们去合成一个武将卡。",
        guide_101_2 = "收集所有武将碎片时能合成为武将卡。请点击武将碎片。",
        guide_101_3 = "新的武将也得到了，请整备全军重新出征吧。",
        
        
        guide_200_1 = "点击升级吧",
        guide_200_2 = "这次我们培养士兵，点击士兵培养",
        guide_200_3 = "点击升级，升级需要消耗一定的铜钱和对应道具",
        guide_200_4 = "升级成功点击关闭吧",
        guide_200_5 = "接下来就看主公你的抉择了点击返回",

        guide_300_1 = "点击布阵吧",
        guide_300_2 = "点击偏将按钮设置偏将吧",
        guide_300_3 = "点击此处添加偏将",
        guide_300_4 = "就选择他作为偏将吧上阵偏将属性的10%会叠加到所有上阵的武将身上",
        guide_300_5 = "这次就选他吧",
        guide_300_6 = "布置完毕点击返回",
        guide_300_7 = "接下来保存布阵信息",
        guide_300_8 = "以后记得有更多位置上阵偏将的时候千万别错过哦，点击返回",

        guide_500_1 = "点击天梯",
        guide_500_2 = "就挑战他吧",
        guide_500_3 = "输赢不重要开战吧",
        guide_500_4 = "去布阵一个防御阵型吧",
        guide_500_5 = "点击返回吧",

        guide_400_1 = "点击主城吧",
        guide_400_2 = "点击武将放入框",
        guide_400_3 = "这次我们就选他吧",
        guide_400_4 = "点击确定吧",
        guide_400_5 = "点击开始执行，接下来就等待任务完成吧",
        guide_400_6 = "点击返回吧",
        guide_400_7 = "请点击确定吧",

        guide_600_1 = "点击七星坛吧",
        guide_600_2 = "选择一个真以上英雄卡吧",
        guide_600_3 = "就选他吧",
        guide_600_4 = "点击确定，就可以点击已经激活的印记，然后通过刷新就能刷新里面的属性了",
        guide_600_5 = "这次选择真印",
        guide_600_6 = "点击刷新，若无符印需要消耗20元宝，每次在刷新时还应该注意下是否还有符印",
        guide_600_7 = "点击确定吧",
        guide_600_8 = "点击返回吧",

        guide_13_1 = "点击第4关卡",
        guide_13_2 = "点击扫荡",
        guide_13_3 = "继续",
        guide_13_4 = "点击确定，这些奖励都是你的了",
        guide_13_5 = "好了，扫荡你也会了，我们回主城吧。",
        guide_13_6 = "点击返回",
        guide_13_7 = "我们现在去看看今天有哪些可以做的任务",
        guide_13_8 = "扫荡一次，点击继续",
        
        guide_800_1 = "在武将训练每天可获得4星以上的高等级武将。",
        guide_800_2 = "每一天登场力，术，魔属性的武将。了解一下获取方法吧?",

        guide_900_1 = "请直接挑战血战吧。",
        guide_900_2 = "因为是第一次，简单去试一下普通难度吧？",

        guide_105_1 = "点击第4关卡",
        guide_105_2 = "点击扫荡",
        guide_105_3 = "继续",
        guide_105_4 = "点击确定，这些奖励都是你的了",
        guide_105_5 = "好了，扫荡你也会了，我们回主城吧。",
        guide_105_6 = "点击返回",
        guide_105_7 = "我们现在去看看今天有哪些可以做的任务",
        guide_105_8 = "扫荡一次，点击继续",

        guide_1001_1 = "限时神将菜单中登场 4~5星武将和 6星神将。 每次活动期间会登场不同的神将，所以有喜欢的神将时在活动期间抽有利哦！",
        guide_1001_2 = "另外，在每次活动期间根据抽取次数支付积分，并决定排名。抽取排名高的人，将得到单独的额外奖励，不要错过哦！",
        
        guide_1002_1 = "突破各章的第10关时就能挑战精英难度副本。",
        
        
        guide_502_1 = "用从天梯获取的积分，能在积分商店购买商品。",
        guide_502_2 = "请回城吧。",
        guide_502_3 = "我们去积分商城看看吧！",
        
        guide_700_1 = "选择公会菜单的话可以加入或生成公会。",

        language_Rank_6 = "目前没有公会上榜",
        language_Rank_7 = "目前没有玩家上榜",


    ------
    --ActivityHeroPopUI_1="活动时间"
    --ActivityHeroPopUI_2="活动倒计时"
    ------

    }
    
return languageConfig_ch